"""
LendingLoopUSDCUSDE Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LendingLoopUSDCUSDEStrategy
except ImportError:
    from strategy import LendingLoopUSDCUSDEStrategy

__all__ = [
    "LendingLoopUSDCUSDEStrategy",
]
